#ifndef __BIGBUFF_6623__
#define __BIGBUFF_6623__

#include "bsp.h"

//YAW电机速度环参数
#define PID_BIGBUFF_SPEED_DEFAULT \
{\
	BIGBUFF_SPEED_PID_P,\
	BIGBUFF_SPEED_PID_I,\
  BIGBUFF_SPEED_PID_D,\
	BIGBUFF_SPEED_PID_MER,\
	-BIGBUFF_SPEED_PID_MAXINPUT,\
	BIGBUFF_SPEED_PID_MAXINPUT,\
	-BIGBUFF_SPEED_PID_MAXOUTPUT,\
	BIGBUFF_SPEED_PID_MAXOUTPUT,\
	BIGBUFF_SPEED_PID_I_MAX,\
	{0.0,0.0},\
	0.0,\
	0.0,\
	0.0,\
	BIGBUFF_SPEED_PID_DEAD,\
}\

#define BIGBUFF_SPEED_PID_P 110//44//44//45	//30  
#define BIGBUFF_SPEED_PID_I 0.14//0.03	//0.02
#define BIGBUFF_SPEED_PID_D 0
#define BIGBUFF_SPEED_PID_MER 30	//最大偏差输入
#define BIGBUFF_SPEED_PID_MAXINPUT 100	//最大期望输入
#define BIGBUFF_SPEED_PID_MAXOUTPUT 6500//7000	//最大输出
#define BIGBUFF_SPEED_PID_I_MAX 2700/BIGBUFF_SPEED_PID_I	//I累加限制
#define BIGBUFF_SPEED_PID_DEAD 0	//计算死区

void Bigbuff_Task(void);

#endif
